name: Python Package Installation

on:
  push:
    branches:
      - main

jobs:
  install-packages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Replace 'x' with the desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run your Python script
      run: python your_script.py  # Replace 'your_script.py' with the name of your Python script
